server:
  port: 9527

spring:
  application:
    name: learing-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/    # 集群配置
  instance:
    instance-id: gateway-9527.com    # eureka 中的别名
    prefer-ip-address: true    # 访问路径可以显示 ip

zuul:
  routes:
    dept.serviceId: learning-consumer-dept-feign    # 微服务真实名称
    dept.path: /dept/**    # 在 gateway 中映射的路径
  ignored-services: learning-consumer-dept-feign    # 禁用真实微服务名称访问
  prefix: /learning    # 访问地址前缀

info:
  app.name: springcloud-learning
  author.name: sunhao
  build.artifactId: $project.artifactId$
  build.version: $project.version$