server:
  port: 3344

spring:
  application:
    name: learning-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SunHaoer/springcloud-learning-config.git
#          username:
#          password:

  