server:
  port: 8080

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: learning-consumer-dept-feign

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/    # 集群配置
  instance:
    instance-id: consumer-dept-feign    # eureka 中的别名
    prefer-ip-address: true    # 访问路径可以显示 ip